---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/adambkaplan/redhat-appstudio-infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-argocd-staging-namespace
